markdown: kramdown 
pygments: true
#Site Setting 
author: canonxu
url: http://canonxu.com
website: canonxu@yeah.net

#Build  Setting 
permalink: /:year/:month/:title/
#highlighter: rouge
paginate: 24
